"""Sourced access flags: free angling (Freiangelrecht, no permit) and SaNa exemptions.

Only flags with an official source (cantonal page, regulation or concordat text) are listed.
Everything else stays 'unknown'. Checked 2026-10-06.
  FREE: (canton, slug regex) -> shore free-angling right; sana = 'not-required' | 'required' | 'unknown'
  SANA_SHORT: canton -> whether short-term permits (< 1 month) are available without SaNa.
"""
from cantons_cfg import T

CHECKED = '2026-10-06'

def F(cantons_slugs, url, label, rule, sana='unknown', season=None):
    return {'match': cantons_slugs, 'url': url, 'label': label, 'rule': rule, 'sana': sana, 'season': season}

R_GENERIC = T('Vom Ufer aus ohne Patent: eine Rute, einfacher Haken ohne Widerhaken, natürlicher Köder (keine Köderfische). Schonzeiten und Mindestmasse gelten.',
              'From the shore without a permit: one rod, single barbless hook, natural bait (no bait fish). Closed seasons and minimum sizes apply.',
              'Depuis la rive sans permis : une canne, hameçon simple sans ardillon, appât naturel (pas de poisson d’appât). Périodes de protection et tailles minimales applicables.',
              'Dalla riva senza patente: una canna, amo singolo senza ardiglione, esca naturale (niente pesci esca). Valgono periodi di divieto e misure minime.')
R_FLOAT = T('Ohne Patent: eine schwimmende Angel mit festem Zapfen und einfachem Haken (Konkordatsregel). Kinder < 14 J. mit weiteren Möglichkeiten.',
            'Without a permit: one floating line with fixed float and single hook (concordat rule). Extra options for children under 14.',
            'Sans permis : une ligne flottante munie d’un flotteur fixe et d’un hameçon simple (règle du concordat). Possibilités supplémentaires pour les enfants de moins de 14 ans.',
            'Senza patente: una lenza galleggiante con galleggiante fisso e amo singolo (regola del concordato). Possibilità supplementari per bambini sotto i 14 anni.')
R_NE = T('Ohne Patent: bis 3 schwimmende Angeln mit festem Zapfen und einfachem Haken, vom Ufer oder Boot (Konkordat Neuenburgersee).',
         'Without a permit: up to 3 floating lines with fixed float and single hook, from shore or boat (Lake Neuchâtel concordat).',
         'Sans permis : jusqu’à 3 lignes flottantes avec flotteur fixe et hameçon simple, de terre ou d’une embarcation (concordat lac de Neuchâtel).',
         'Senza patente: fino a 3 lenze galleggianti con galleggiante fisso e amo singolo, da riva o barca (concordato lago di Neuchâtel).')

FREE = [
    F([('ZH', r'^(zuerichsee|greifensee|pfaeffikersee|tuerlersee)')],
      'https://www.zh.ch/content/dam/zhweb/bilder-dokumente/themen/umwelt-tiere/tiere/fischerei-und-jagd/fischerei/wie_werde_ich_angelfischerin_wo_darf_ich_fischen/merkblatt_freiangelfischerei.pdf',
      'Merkblatt Freiangelfischerei Kanton Zürich (Juni 2026)',
      T('Vom trockenen Ufer ohne Patent: eine Rute oder Schnur, ein Köder mit Einfachhaken ohne Widerhaken; natürliche Köder, Lebensmittel, künstliche Fliegen (max. Hakengrösse 8), keine Köderfische. Zürichsee: 04–23 Uhr (Sommerzeit) bzw. 05–22 Uhr.',
        'From dry shore without a permit: one rod or line, one bait on a single barbless hook; natural bait, food, artificial flies (hook size ≤ 8), no bait fish. Lake Zurich: 04–23 h (summer time) / 05–22 h.',
        'Depuis la rive sèche sans permis : une canne ou ligne, un appât sur hameçon simple sans ardillon ; appâts naturels, aliments, mouches (hameçon ≤ 8), pas de poisson d’appât. Lac de Zurich : 4–23 h (été) / 5–22 h.',
        'Dalla riva asciutta senza patente: una canna o lenza, un’esca su amo singolo senza ardiglione; esche naturali, alimenti, mosche (amo ≤ 8), niente pesci esca. Lago di Zurigo: 4–23 (estate) / 5–22.')),
    F([('BE', r'^(brienzersee|thunersee|bielersee)')],
      'https://www.weu.be.ch/de/start/themen/jagd-fischerei/fischerei/fischen-kanton-bern/fischen-ohne-angelpatent.html',
      'Kanton Bern · Fischen ohne Angelpatent',
      T('Vom Ufer aus ohne Patent und ohne SaNa: eine Angelrute, einfacher Haken ohne Widerhaken; keine Köderfische.',
        'From the shore without a permit and without SaNa: one rod, single barbless hook; no bait fish.',
        'Depuis la rive sans permis et sans SaNa : une canne, hameçon simple sans ardillon ; pas de poisson d’appât.',
        'Dalla riva senza patente e senza SaNa: una canna, amo singolo senza ardiglione; niente pesci esca.'),
      sana='not-required'),
    F([('LU', r'^vierwaldstaettersee')], 'https://lawa.lu.ch/fischerei/angelfischerei/vierwaldstaettersee', 'Kanton Luzern · Fischereiausübung Vierwaldstättersee',
      T('Luzerner Teil: kostenlos ohne Patent von öffentlich zugänglichen Ufern, Brücken und Stegen; einfache Angel ohne Widerhaken, nur natürliche Köder, keine Köderfische.',
        'Lucerne part: free without a permit from publicly accessible shores, bridges and jetties; single barbless hook, natural bait only, no bait fish.',
        'Partie lucernoise : gratuit sans permis depuis rives, ponts et pontons publics ; hameçon simple sans ardillon, appâts naturels uniquement.',
        'Parte lucernese: gratis senza patente da rive, ponti e pontili pubblici; amo singolo senza ardiglione, solo esche naturali.')),
    F([('LU', r'^sempachersee')], 'https://lawa.lu.ch/fischerei/angelfischerei/sempachersee', 'Kanton Luzern · Fischereiausübung Sempachersee', None),
    F([('ZG', r'^zugersee')], 'https://cdn.zg.ch/dam/jcr:f42a4598-6972-4cab-895b-2f8becc0d9d7/Zugerseekarte%20Angelfischerei%20November%202021%20inkl.%20R%C3%BCckseite.pdf',
      'Kanton Zug · Zugerseekarte Angelfischerei (§ 13 Freiangelfischerei)',
      T('Patentfrei vom Ufer: eine Rute, einfacher Haken ohne Widerhaken mit Schwimmer und natürlichem Köder; keine Köderfische, Löffel, Spinner. Privatfischenzen/Verbotszonen beachten.',
        'Permit-free from the shore: one rod, single barbless hook with float and natural bait; no bait fish, spoons, spinners. Mind private fishing rights and no-fishing zones.',
        'Sans permis depuis la rive : une canne, hameçon simple sans ardillon avec flotteur et appât naturel ; pas de poisson d’appât, cuillère, spinner.',
        'Senza patente dalla riva: una canna, amo singolo senza ardiglione con galleggiante ed esca naturale; niente pesci esca, cucchiaini, spinner.')),
    F([('SZ', r'^(vierwaldstaettersee|zugersee|zuerichsee|lauerzersee|itlimoos)')],
      'https://www.sz.ch/verwaltung/umweltdepartement/amt-fuer-gewaesser/fischerei/haeufig-gestellte-fragen.html/8756-8758-8802-9447-9450-10713-10821',
      'Kanton Schwyz · Häufig gestellte Fragen Fischerei',
      T('Freiangelrecht vom Ufer (eine Rute, einfache Angel ohne Widerhaken, Schwimmer, nur natürlicher Köder). Achtung: kostenlose Freiangelkarte nötig und SaNa-Pflicht (unter 14 J. befreit). Nicht am Sihl-, Wägitaler-, Stoossee.',
        'Free angling from the shore (one rod, single barbless hook, float, natural bait only). Note: free Freiangelkarte required and SaNa mandatory (under 14 exempt). Not on Sihlsee, Wägitalersee, Stoossee.',
        'Droit de pêche libre depuis la rive (une canne, hameçon simple sans ardillon, flotteur, appât naturel). Attention : carte gratuite obligatoire et SaNa exigé (moins de 14 ans exemptés).',
        'Pesca libera dalla riva (una canna, amo singolo senza ardiglione, galleggiante, solo esca naturale). Attenzione: tessera gratuita obbligatoria e SaNa richiesto (sotto i 14 anni esenti).'),
      sana='required'),
    F([('SG', r'^bodensee')], 'https://www.sg.ch/umwelt-natur/jagd-fischerei/fischerei/fischereipatente/freiangelrecht.html', 'Kanton St. Gallen · Freiangelrecht',
      T('Vom Ufer ohne Patent: eine Rute, einfache Angel mit Zapfen, natürlicher Köder (keine Köderfische). Ohne SaNa: Widerhakenverbot und keine Lebendhälterung.',
        'From the shore without a permit: one rod, single hook with float, natural bait (no bait fish). Without SaNa: barbless only, no keeping fish alive.',
        'Depuis la rive sans permis : une canne, hameçon simple avec flotteur, appât naturel. Sans SaNa : sans ardillon, pas de garde vivante.',
        'Dalla riva senza patente: una canna, amo singolo con galleggiante, esca naturale. Senza SaNa: senza ardiglione, niente conservazione in vivo.'),
      sana='not-required'),
    F([('SG', r'^(walensee|zuerichsee)'), ('GL', r'^walensee')], 'https://www.sg.ch/umwelt-natur/jagd-fischerei/fischerei/fischereipatente/freiangelrecht.html', 'Kanton St. Gallen · Freiangelrecht (Walensee/Zürichsee, interkantonal)',
      T('Vom Ufer ohne Patent: eine Rute oder Schnur, ein Köder mit einfachem Haken; natürliche Köder, Lebensmittel, künstliche Fliegen; keine Köderfische.',
        'From the shore without a permit: one rod or line, one bait on a single hook; natural bait, food, artificial flies; no bait fish.',
        'Depuis la rive sans permis : une canne ou ligne, un appât sur hameçon simple ; appâts naturels, aliments, mouches ; pas de poisson d’appât.',
        'Dalla riva senza patente: una canna o lenza, un’esca su amo singolo; esche naturali, alimenti, mosche; niente pesci esca.')),
    F([('GL', r'^kloentalersee')], 'https://www.gl.ch/public/upload/assets/3670/Freiangelrecht_Kloentalersee.pdf', 'Kanton Glarus · Freiangelrecht Klöntalersee',
      T('Vom Ufer ohne Patent: eine Rute, einfache Angel ohne Widerhaken, natürlicher Köder oder künstliche Fliege; keine Köderfische oder Kunstköder.',
        'From the shore without a permit: one rod, single barbless hook, natural bait or artificial fly; no bait fish or lures.',
        'Depuis la rive sans permis : une canne, hameçon simple sans ardillon, appât naturel ou mouche ; pas de leurres.',
        'Dalla riva senza patente: una canna, amo singolo senza ardiglione, esca naturale o mosca; niente esche artificiali.')),
    F([('TG', r'^(bodensee|untersee)')], 'https://jfv.tg.ch/fischerei/freiangelei.html/8656', 'Jagd- und Fischereiverwaltung Thurgau · Freiangelei',
      T('Uferfischerei für jedermann frei (ausser Fischenzen/Verbotszonen): eine Rute mit festem Zapfen, einfacher Haken ohne Widerhaken, keine Kunstköder/Köderfische. Kein SaNa nötig.',
        'Shore fishing free for everyone (except private Fischenzen/no-fishing zones): one rod with fixed float, single barbless hook, no lures/bait fish. No SaNa needed.',
        'Pêche depuis la rive libre pour tous (sauf droits privés/zones interdites) : une canne avec flotteur fixe, hameçon simple sans ardillon. Pas de SaNa.',
        'Pesca da riva libera per tutti (salvo diritti privati/zone vietate): una canna con galleggiante fisso, amo singolo senza ardiglione. Nessun SaNa.'),
      sana='not-required'),
    F([('UR', r'^vierwaldstaettersee')], 'https://www.ur.ch/dienstleistungen/4912', 'Kanton Uri · Fischen (Merkblatt Angelfischerei)',
      T('An öffentlichen Ufern des Urnersees (und Seelisbergersees) ohne Patent: einfache Rute, Einzelhaken ohne Widerhaken, nur natürlicher Köder.',
        'From public shores of Lake Uri (and Seelisbergersee) without a permit: simple rod, single barbless hook, natural bait only.',
        'Depuis les rives publiques du lac d’Uri sans permis : canne simple, hameçon sans ardillon, appât naturel uniquement.',
        'Dalle rive pubbliche del lago di Uri senza patente: canna semplice, amo senza ardiglione, solo esca naturale.')),
    F([('NW', r'^vierwaldstaettersee')], 'https://gesetze.nw.ch/api/de/versions/1389/pdf_file', 'Kanton Nidwalden · Fischereigesetz (kFG) Art. 6',
      T('Im Vierwaldstättersee ist der Fischfang vom Ufer aus ohne Patent gestattet, sofern kein Widerhaken verwendet wird.',
        'On Lake Lucerne, fishing from the shore without a permit is allowed if no barbed hook is used.',
        'Dans le lac des Quatre-Cantons, la pêche depuis la rive est permise sans permis si aucun ardillon n’est utilisé.',
        'Nel lago dei Quattro Cantoni la pesca dalla riva è consentita senza patente se non si usa l’ardiglione.')),
    F([('OW', r'^(sarnersee|vierwaldstaettersee)')], 'https://www.ow.ch/_docn/435695/Merkblatt_Fischerei_2026.PDF', 'Kanton Obwalden · Merkblatt Fischerei 2026',
      T('Sarner- und Alpnachersee: vom 1. April bis 15. Oktober vom Ufer aus ohne Patent; eine Rute, einfacher Haken ohne Widerhaken, natürlicher Köder (keine Fische), keine Löffel/Spinner.',
        'Sarnersee and Alpnachersee: 1 April – 15 October from the shore without a permit; one rod, single barbless hook, natural bait (no fish), no spoons/spinners.',
        'Sarnersee et Alpnachersee : du 1er avril au 15 octobre depuis la rive sans permis ; une canne, hameçon sans ardillon, appât naturel.',
        'Sarnersee e Alpnachersee: dal 1° aprile al 15 ottobre dalla riva senza patente; una canna, amo senza ardiglione, esca naturale.'),
      season='04-01/10-15'),
    F([('GE', r'^genfersee')], 'https://www.ge.ch/permis-peche/conditions-pecher-sans-permis', 'ge.ch · Conditions pour pêcher sans permis', R_FLOAT),
    F([('VD', r'^genfersee'), ('VS', r'^leman')], 'https://silgeneve.ch/legis/data/rsg_m4_03p01.htm', 'Règlement d’exécution du concordat sur la pêche dans le lac Léman (RCPL)', R_FLOAT),
    F([('VD', r'^(neuenburgersee)'), ('NE', r'^neuenburgersee'), ('FR', r'^neuenburgersee')],
      'https://www.vd.ch/fileadmin/user_upload/themes/environnement/biodiversite/fichiers_pdf/P%C3%AAche/D%C3%A9couvrez_la_p%C3%AAche_dans_le_canton_de_Vaud__/DGE_Reglement_2026_Neuchatel_Def.pdf',
      'Règlement concordat lac de Neuchâtel 2026 (publié par VD)', R_NE),
    F([('VD', r'^murtensee'), ('FR', r'^murtensee')],
      'https://www.vd.ch/fileadmin/user_upload/themes/environnement/faune_nature/fichiers_pdf/peche/01_Decouvrez_la_peche_dans_le_canton_de_VD/Extrait_Reglement_Morat.pdf',
      'Règlement concordat lac de Morat (extrait VD)', R_FLOAT),
    F([('VD', r'^(lac-de-joux|lac-brenet)')],
      'https://www.vd.ch/fileadmin/user_upload/themes/environnement/biodiversite/fichiers_pdf/P%C3%AAche/D%C3%A9couvrez_la_p%C3%AAche_dans_le_canton_de_Vaud__/DGE_Reglement_2026_Joux_Def.pdf',
      'Règlement lacs de Joux, Brenet et Ter 2026 (VD)', R_FLOAT),
]
for f in FREE:
    if f['rule'] is None:
        f['rule'] = R_GENERIC

S = lambda v, url, label, note, only=None: {'v': v, 'url': url, 'label': label, 'note': note, 'only': only}
SANA_SHORT = {
    'ZH': S('yes', 'https://www.zh.ch/content/dam/zhweb/bilder-dokumente/themen/umwelt-tiere/tiere/fischerei-und-jagd/fischerei/verf%C3%BCgungen/fischereivorschriften_auszug_fuer_die_angelfischerei_202603.pdf',
            'Fischereivorschriften ZH (Auszug Angelfischerei, ab 1.1.2026)',
            T('SaNa erst für Berechtigungen ab 1 Monat – Tagespatent ohne SaNa.', 'SaNa only for permits of 1 month or more – day permit without SaNa.',
              'SaNa seulement pour les permis d’un mois ou plus – permis journalier sans SaNa.', 'SaNa solo per patenti da 1 mese – patente giornaliera senza SaNa.')),
    'BE': S('yes', 'https://www.weu.be.ch/de/start/themen/jagd-fischerei/fischerei/fischen-kanton-bern/fischereipatent-beziehen.html', 'Kanton Bern · Fischereipatent beziehen',
            T('Tages-/Wochenpatente ohne SaNa; Monats- und Jahrespatente nur mit SaNa.', 'Day/week permits without SaNa; month/annual permits require SaNa.',
              'Permis jour/semaine sans SaNa ; mois/année avec SaNa.', 'Patenti giorno/settimana senza SaNa; mese/anno con SaNa.')),
    'LU': S('yes', 'https://lawa.lu.ch/fischerei/fischereipatente', 'Kanton Luzern · Fischereipatent lösen',
            T('Jahrespatente nur mit SaNa; Monats- und Kurzzeitpatente ohne SaNa (Porträtfoto nötig).', 'Annual permits require SaNa; monthly and shorter permits without SaNa (portrait photo needed).',
              'Permis annuels avec SaNa ; permis mensuels et plus courts sans SaNa.', 'Patenti annuali con SaNa; mensili e più brevi senza SaNa.')),
    'GR': S('yes', 'https://www.gr.ch/DE/institutionen/verwaltung/diem/ajf/fischerei/Fischen-in-Graubuenden/Seiten/Fischereipatente.aspx', 'AJF Graubünden · Fischereipatente',
            T('Tages-, Wochen- und Halbmonatspatente ohne SaNa; Monats- und Saisonpatente mit SaNa.', 'Day, week and half-month permits without SaNa; month and season permits require SaNa.',
              'Permis jour, semaine et demi-mois sans SaNa ; mois et saison avec SaNa.', 'Patenti giorno, settimana e mezzo mese senza SaNa; mese e stagione con SaNa.')),
    'VS': S('yes', 'https://valais-peche.ch/wp-content/uploads/2024/02/Arrete-cantonal-2024-2028.pdf', 'Arrêté quinquennal sur l’exercice de la pêche en Valais 2024–2028',
            T('Permis journalier (1–2 jours) sans SaNa (dépliant d’information remis).', 'Day permit (1–2 days) without SaNa (information leaflet provided).',
              'Permis journalier (1–2 jours) sans SaNa (dépliant d’information remis).', 'Permesso giornaliero (1–2 giorni) senza SaNa.')),
    'UR': S('yes', 'https://www.ur.ch/dienstleistungen/4912', 'Kanton Uri · Fischen',
            T('Nur das 1-Tages-Patent (Göscheneralpstausee, Urner- und Seelisbergersee) ist ohne SaNa; 3-Tage-, Wochen- und Jahrespatent mit SaNa.',
              'Only the 1-day permit (Göscheneralpstausee, Lake Uri, Seelisbergersee) is without SaNa; 3-day, week and annual permits require SaNa.',
              'Seul le permis d’un jour (Göscheneralp, lac d’Uri, Seelisberg) est sans SaNa.', 'Solo la patente di 1 giorno (Göscheneralp, lago di Uri, Seelisberg) è senza SaNa.'),
            only=r'^(goescheneralp|vierwaldstaettersee|seelisberg)'),
    'SZ': S('no', 'https://www.sz.ch/verwaltung/umweltdepartement/amt-fuer-gewaesser/fischerei/fischerpatente.html/8756-8758-8802-9447-9450-10713-10826', 'Kanton Schwyz · Fischerpatente',
            T('SaNa-Pflicht für alle Patente und für das Freiangelrecht (Ausnahme: Jugendliche unter 14 J. mit Begleitperson).', 'SaNa required for all permits and free angling (exception: under 14 with accompanying adult).',
              'SaNa exigé pour tous les permis et la pêche libre (sauf moins de 14 ans accompagnés).', 'SaNa richiesto per tutte le patenti e la pesca libera (salvo sotto i 14 anni accompagnati).')),
    'TG': S('no', 'https://www.rechtsbuch.tg.ch/api/de/versions/2593/pdf_file_with_annexes', 'Fischereiverordnung TG (RB 923.11) § 7',
            T('Für jede Fischereibewilligung ist der SaNa erforderlich; ausgenommen ist nur die Freiangelei.', 'SaNa is required for every fishing permit; only free angling is exempt.',
              'SaNa exigé pour tout permis ; seule la pêche libre en est exemptée.', 'SaNa richiesto per ogni patente; esente solo la pesca libera.')),
}
